### ISSUE TITLE
Loader issue when used in ScrollView with keyboard

### ISSUE THREAD

**Issue by vivekmzkl** [Changemin/LoadingButton#3]
The loader is misbehaving (animating from top to bottom) when the keyboard is dismissed inside a scroll view.

![IMG_3A4073EE9A1A-1](https://user-images.githubusercontent.com/47320606/126279688-7d33b54c-b45f-407e-a50f-dd7162c42ac0.jpeg)

**Comment by byunkyungmin** [comment]
Thank YOU for the issue! Could you give me some of your code to refer?

**Comment by macakdev** [comment]
@changemin , @vivekmzkl , please have a look at following pull request. It should fix this problem.

https://github.com/changemin/LoadingButton/pull/4
